In [85]:
import pandas as pd
import numpy as np
import pickle as pkl

In [47]:
# Read in file of transporter genes
filepath = '../Transporters_TCDB.txt'

tp_df = pd.read_csv(filepath,sep=None,engine='python',header=None)

In [87]:
# Read in file of enzyme genes
# filepath = '../Enzyme_genes.txt'
filepath = '../Enzyme_genes2.xlsx'

en_df = pd.read_excel(filepath,sep=None)

In [88]:
en_df

,Entry,Entry name,Status,Protein names,Gene names,Organism,Length
0,O15254,ACOX3_HUMAN,reviewed,Peroxisomal acyl-coenzyme A oxidase 3 (EC 1.3....,ACOX3 BRCOX PRCOX,Homo sapiens (Human),700
1,Q16671,AMHR2_HUMAN,reviewed,Anti-Muellerian hormone type-2 receptor (EC 2....,AMHR2 AMHR MISR2,Homo sapiens (Human),573
2,Q9GZX7,AICDA_HUMAN,reviewed,Single-stranded DNA cytosine deaminase (EC 3.5...,AICDA AID,Homo sapiens (Human),198
3,P18440,ARY1_HUMAN,reviewed,Arylamine N-acetyltransferase 1 (EC 2.3.1.5) (...,NAT1 AAC1,Homo sapiens (Human),290
4,Q9NR71,ASAH2_HUMAN,reviewed,Neutral ceramidase (N-CDase) (NCDase) (EC 3.5....,ASAH2 HNAC1,Homo sapiens (Human),780
...,...,...,...,...,...,...,...
3675,Q8WVY7,UBCP1_HUMAN,reviewed,Ubiquitin-like domain-containing CTD phosphata...,UBLCP1,Homo sapiens (Human),318
3676,P63146,UBE2B_HUMAN,reviewed,Ubiquitin-conjugating enzyme E2 B (EC 2.3.2.23...,UBE2B RAD6B,Homo sapiens (Human),152
3677,P09936,UCHL1_HUMAN,reviewed,Ubiquitin carboxyl-terminal hydrolase isozyme ...,UCHL1,Homo sapiens (Human),223
3678,Q93009,UBP7_HUMAN,reviewed,Ubiquitin carboxyl-terminal hydrolase 7 (EC 3....,USP7 HAUSP,Homo sapiens (Human),1102
3679,P63125,VPK25_HUMAN,reviewed,Endogenous retrovirus group K member 25 Pro pr...,ERVK-25,Homo sapiens (Human),156

In [89]:
en_gene_names = en_df['Gene names'].tolist()

In [90]:
nan_cnt = 0
en_gene_list = []

for genes in en_gene_names:
    try:
        en_gene_list.extend(genes.split())
    except:
        nan_cnt += 1

In [91]:
en_names= np.unique(en_gene_list)

In [92]:
tp_df.columns = ['Name','Description','Misc']

In [93]:
tp_names = tp_df['Name'].unique().tolist()

In [94]:
combined_names = list(np.unique(tp_names + list(en_names)))

In [95]:
pkl.dump(combined_names, open( "../combined_names.pkl", "wb" ) )

In [96]:
ens_table = pd.read_csv('../Ensembl_symbol_entrez.csv')

In [97]:
ens_table

,ensembl_gene_id,external_gene_name,entrezgene_id,gene_biotype,description
0,ENSG00000000003,TSPAN6,7105.0,protein_coding,tetraspanin 6 [Source:HGNC Symbol;Acc:HGNC:11858]
1,ENSG00000000005,TNMD,64102.0,protein_coding,tenomodulin [Source:HGNC Symbol;Acc:HGNC:17757]
2,ENSG00000000419,DPM1,8813.0,protein_coding,dolichyl-phosphate mannosyltransferase subunit...
3,ENSG00000000457,SCYL3,57147.0,protein_coding,SCY1 like pseudokinase 3 [Source:HGNC Symbol;A...
4,ENSG00000000460,C1orf112,55732.0,protein_coding,chromosome 1 open reading frame 112 [Source:HG...
...,...,...,...,...,...
56714,ENSG00000281904,AC233263.6,NaN,lncRNA,novel transcript
56715,ENSG00000281909,HERC2P7,NaN,unprocessed_pseudogene,hect domain and RLD 2 pseudogene 7 [Source:HGN...
56716,ENSG00000281910,SNORA50A,NaN,snoRNA,"small nucleolar RNA, H/ACA box 50A [Source:HGN..."
56717,ENSG00000281912,LINC01144,NaN,lncRNA,long intergenic non-protein coding RNA 1144 [S...
56718,ENSG00000281920,AC007389.5,NaN,lncRNA,novel transcript

In [98]:
combined_names_df = pd.DataFrame(combined_names)
combined_names_df.columns = ['external_gene_name']

In [99]:
combined_names_df

     external_gene_name
0                 101F6
1                  12LO
2                15E1.2
3                   2DD
4                   3BH
...                 ...
8913            hucep-6
8914              polmu
8915              x0003
8916              x0005
8917              x0008

[8918 rows x 1 columns]

In [100]:
names_df = pd.merge(ens_table,combined_names_df)

In [110]:
names_df.to_csv('../ensembl_index.csv')

In [111]:
names_df

,ensembl_gene_id,external_gene_name,entrezgene_id,gene_biotype,description
0,ENSG00000000419,DPM1,8813.0,protein_coding,dolichyl-phosphate mannosyltransferase subunit...
1,ENSG00000000938,FGR,2268.0,protein_coding,"FGR proto-oncogene, Src family tyrosine kinase..."
2,ENSG00000001036,FUCA2,2519.0,protein_coding,alpha-L-fucosidase 2 [Source:HGNC Symbol;Acc:H...
3,ENSG00000001084,GCLC,2729.0,protein_coding,glutamate-cysteine ligase catalytic subunit [S...
4,ENSG00000001561,ENPP4,22875.0,protein_coding,ectonucleotide pyrophosphatase/phosphodiestera...
...,...,...,...,...,...
4205,ENSG00000278053,DDX52,11056.0,protein_coding,DExD-box helicase 52 [Source:HGNC Symbol;Acc:H...
4206,ENSG00000278535,DHRS11,79154.0,protein_coding,dehydrogenase/reductase 11 [Source:HGNC Symbol...
4207,ENSG00000278540,ACACA,31.0,protein_coding,acetyl-CoA carboxylase alpha [Source:HGNC Symb...
4208,ENSG00000278619,MRM1,79922.0,protein_coding,mitochondrial rRNA methyltransferase 1 [Source...
4209,ENSG00000279782,PPIAL4F,728945.0,protein_coding,peptidylprolyl isomerase A like 4F [Source:HGN...

In [112]:
combined_names_df

     external_gene_name
0                 101F6
1                  12LO
2                15E1.2
3                   2DD
4                   3BH
...                 ...
8913            hucep-6
8914              polmu
8915              x0003
8916              x0005
8917              x0008

[8918 rows x 1 columns]